feat: update AMI extraction to handle multiple AMIs and fix CloudWatch Agent download URL

diff --git a/.github/workflows/build-ami.yaml b/.github/workflows/build-ami.yaml
--- a/.github/workflows/build-ami.yaml
+++ b/.github/workflows/build-ami.yaml
@@ -58,11 +58,14 @@ jobs:
           cd packer
           packer build . | tee packer_build_output.log
 
-      - name: Extract AMI ID
-        id: get_ami_id
+      - name: Extract AMI IDs
+        id: get_ami_ids
         run: |
-          AMI_ID=$(grep -oP '(?<=us-west-2: )ami-[a-zA-Z0-9]+' packer/packer_build_output.log)
-          [ -z "$AMI_ID" ] && { echo "Error: AMI ID is empty"; exit 1; }
-          echo "AMI ID is $AMI_ID"
-          echo "$AMI_ID" > ami_id.txt
-          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
+          MYSQL_AMI=$(grep -A 1 "amazon-ebs.mysql: AMIs were created:" packer/packer_build_output.log | grep -oP 'ami-[a-zA-Z0-9]+')
+          WEBAPP_AMI=$(grep -A 1 "amazon-ebs.webapp: AMIs were created:" packer/packer_build_output.log | grep -oP 'ami-[a-zA-Z0-9]+')
+
+          [ -z "$MYSQL_AMI" ] && { echo "Error: MYSQL AMI ID is empty"; exit 1; }
+          [ -z "$WEBAPP_AMI" ] && { echo "Error: WEBAPP AMI ID is empty"; exit 1; }
+
+          echo "MYSQL AMI ID is $MYSQL_AMI"
+          echo "WEBAPP AMI ID is $WEBAPP_AMI"
